### ISSUE TITLE
sserangecoding usage

### ISSUE THREAD

**Issue by powturbo** [richgel999/sserangecoding#2]
Hi,
I've integrated sserangecoding into [TurboBench](https://github.com/powturbo/TurBoBench).
Unfortnately I'm becoming a compare error after decompression. 
Can you please take a short look at it [here](https://github.com/powturbo/TurboBench/blob/7f494ba43ba2758ba7148f58eb76657ed07a7005/plugins.cc#L863).
Thank you!

**Comment by richgel999** [comment]
Cool I'm checking it out. 

On the data that it failed on, does running "sserangecoding filename" work correctly?
Or you can use "sserangecoding c filename comp", then "sserangecoding d comp decomp".

**Comment by richgel999** [comment]
Looking at your code that you showed me, I don't see a call to `vrange_init()`. This must be called first before using the codec, otherwise some global tables won't be initialized:

https://github.com/richgel999/sserangecoding/blob/main/sserangecoder.h#LL47C7-L47C18

I also searched your entire project, and don't see a call to `vrange_init()` anywhere. That would definitely cause the decoder to not work. (I'll add an assert to detect this.)

**Comment by powturbo** [comment]
Thank  you, now it works fine. 
Are you using other functions in your benchmarks presented in your blog?
People at [encode.su](https://encode.su/threads/1821-Asymetric-Numeral-System?p=79241&viewfull=1#post79241) are wondering about your timings and conclusions

**Comment by richgel999** [comment]
All the benchmark code is in the repo here:

https://github.com/richgel999/sserangecoding/blob/main/test.cpp

Just run it and it'll load "book1" from the current directory and encode & decode. There's nothing particularly fancy going on here, and I've tested this on multiple AMD and Intel machines. I've been using this in my LZ codecs for around a month. It's fairly standard 24-bit range coding using `_mm_div_ps()`, with the source bytes fetched from an interleaved stream.

Just ran the code in the repo again after compiling with Visual Studio 2019:

![image](https://github.com/richgel999/sserangecoding/assets/6934809/7d5f9bcf-f965-405e-94d0-91ed7f04d051)

gcc/clang gets similar perf.

**Comment by richgel999** [comment]
BTW - the particular range coding algorithm I'm using is (as far as I can tell) Subbotin's from the late 90's. I just changed it to be 24-bits so the _mm_div_ps() works, and interleaved the streams so a shuffle can be used. Otherwise it's bog standard stuff.

I don't have an encode.su login so I can't comment. They can try to censor these results all they want, but the code is all there for examination. Once you examine the inner loops of vectorized rANS, range, and Huffman decoders they are very similar ultimately.

**Comment by powturbo** [comment]
Your work is still impressive for a range coder.
I've integrated sserangecoder into turbobench since I saw this in one of your tweet.
I've also often criticized the propaganda around ANS in the past. At the end, it's up to the user to figure out which EC 
is best suited to his needs. 
Keep up the good work and your excellent lzXor innovation.

**Comment by richgel999** [comment]
Thanks! I've carefully studied your Turbo Range Coder code, BTW. And your Turbo Histogram code. I will give you credits - it was very educational.

I would appreciate you updating encode.su - and please let them know that the compare error was due to the codec not being initialized. Also, if someone claims they can do rANS using SSE 4.1 faster, then they need to pony up and show us the code or the claim is meaningless. They also need to show us their license to use the technique which is patented in the US.

BTW - porting this range coder to AVX-2 is not difficult. Also, once you understand it, getting Huffman coding working is fairly straightforward in both SSE 4.1 and AVX-2.

**Comment by powturbo** [comment]
Thanks for your nice words.
I've edited my comments and updated the benchmark with the new timings.
Don't take the comments too seriously, you have nothing to prove.
Cheers,

**Comment by richgel999** [comment]
I added links and a thanks to your repo in my README.md:
https://github.com/richgel999/sserangecoding/blob/main/README.md

**Comment by flanglet** [comment]
FWIW nobody is censoring anything at encode.su.  There were some questions like comparing your code with htscodecs RANS implementation and such but it can now be done via TurboBench.

**Comment by richgel999** [comment]
Thanks, I was referring to Wikipedia.
